KTM/KTM.App/Areas/Admin/Controllers/MotorcyclesController.cs
namespace KTM.App.Areas.Admin.Controllers
{
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Linq;
    using System.Web.Mvc;
    using AutoMapper;
    using Data.UnitOfWork;
    using Microsoft.AspNet.Identity;
    using Models.BindingModels;
    using KTM.Models.EntityModels;
    using KTM.Models.ViewModels;
    using Controller = App.Controllers.Controller;

    [Authorize(Roles = "Admin")]
    public class MotorcyclesController : Controller
    {
        public MotorcyclesController(IKTMData data)
            : base(data)
        {
        }
        public ActionResult Index(int page = 1, int count = 5)
        {
            var motorcycles = this.Data.Motorcycles.All()
                .OrderBy(g => g.Title)
                .Skip((page - 1) * count)
                .Take(count);
            ViewBag.MaxPages = (this.Data.Motorcycles.All().Count() + count - 1) / count;
            ViewBag.CurrentPage = page;
            var model = Mapper.Map<IEnumerable<ConciseMotorcycleViewModel>>(motorcycles);

            return this.View(model);
        }

        public ActionResult Details(int id)
        {
            var motorcycle = this.Data.Motorcycles.All()
                .Include(g => g.Category)
                .Include(g => g.Reviews)
                .Include(g => g.Ratings)
                .FirstOrDefault(g => g.Id == id);
            if (motorcycle == null)
            {
                return this.HttpNotFound("The requested motorcycle was not found in the system.");
            }

            var model = Mapper.Map<MotorcycleDetailsViewModel>(motorcycle);
            return this.View(model);
        }



        [HttpGet]
        public ActionResult Add()
        {


            var categories = this.Data.Categories.All()
                .Select(c => new SelectListItem() { Text = c.Name, Value = c.Id.ToString() });
            ViewBag.Categories = categories;
            return this.View(new MotorcycleBindingModel());
        }

        public ActionResult AddImageUrl()
        {
            return this.PartialView("_AddImageUrl", new List<string>() { string.Empty });
        }



        [HttpPost]
        public ActionResult Add(MotorcycleBindingModel motorcycleModel)
        {


            var currentUser = this.Data.Users.Find(this.User.Identity.GetUserId());
            var category = this.Data.Categories.Find(motorcycleModel.CategoryId);
            var imageUrls = motorcycleModel.ImageUrls.Select(url => new ImageUrl() { Url = url }).ToList();
            var motorcycle = new Motorcycle()
            {
                Title = motorcycleModel.Title,
                Description = motorcycleModel.Description,
                Engine = motorcycleModel.Engine,
                Category = category,
                Author = currentUser
            };

            this.Data.Motorcycles.Add(motorcycle);
            this.Data.SaveChanges();
            motorcycle.ImageUrls = imageUrls;
            this.Data.SaveChanges();

            return this.RedirectToAction("Details", "Motorcycles", new { area = "", id = motorcycle.Id });
        }
    }
}

KTM/KTM.App/Controllers/MotorcyclesController.cs
namespace KTM.App.Controllers
{

    using System.Linq;
    using System.Net;
    using System.Web.Mvc;
    using Data.UnitOfWork;
    using Services;

    public class MotorcyclesController : Controller
    {
        private MotorcycleService service;
       

        public MotorcyclesController(IKTMData data)
             : base(data)
        {
            this.service=new MotorcycleService();
            
        }

      

        public ActionResult Index(int page = 1, int count = 5)
        {

              var motorcycles = this.service.GetAllMotorcycles(page, count);
         
            ViewBag.MaxPages = (this.Data.Motorcycles.All().Count() + count - 1) / count;
            ViewBag.CurrentPage = page;
            var vm = this.service.GetViewModels(motorcycles);
            if (vm == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }
            Response.StatusCode = 200;
            return this.View(vm);
        }

        public ActionResult Details(int id)
        {
           
            var vm = this.service.GetDetails(id);
            if (vm == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }
            Response.StatusCode = 200;
            return this.View(vm);
        }

      
    }
}

KTM/KTM.App/Controllers/RatingsController.cs
namespace KTM.App.Controllers
{
    using System.Linq;
    using System.Net;
    using System.Web.Mvc;
    using Data.UnitOfWork;
    using Microsoft.AspNet.Identity;
    using Models.BindingModels;
    using Models.EntityModels;
    using Services;

    public class RatingsController : Controller
    {
       private RatingsService service;

        public RatingsController(IKTMData data)
            : base(data)
        {
          this.service=new RatingsService();
        }

        [Authorize]
        public ActionResult RatingDetails(int id)
        {
         
            var motorcycle = this.Data.Motorcycles.Find(id);
            if (motorcycle == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound,"The requested motorcycle was not found in the system.");
            }

           var currentUser = this.Data.Users.Find(this.User.Identity.GetUserId());

          
           var existingRating = this.Data.Ratings.All().FirstOrDefault(r => r.Motorcycle.Id == motorcycle.Id && r.Author.Id == currentUser.Id);
            if (existingRating != null)
            {
            
               var model = this.service.GetRatingViewModel(existingRating);
                if (model == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.NotFound);
                }
                Response.StatusCode = 200;
                return this.PartialView("_Rating", model);
            }
            else
            {
                Response.StatusCode = 200;
                return this.PartialView("_AddRating", new RatingBindingModel() { MotorcycleId = id });
            }
        }

        [Authorize]
        public ActionResult Add(int id, RatingBindingModel ratingModel)
        {
           var motorcycle = this.Data.Motorcycles.Find(id);
         
            if (motorcycle == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound,"The requested motorcycle was not found in the system.");
            }

            var currentUser = this.Data.Users.Find(this.User.Identity.GetUserId());

          var existingRating = this.Data.Ratings.All().FirstOrDefault(r => r.Motorcycle.Id == motorcycle.Id && r.Author.Id == currentUser.Id);
   
            if (existingRating != null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "You have already rated this motorcycle");
            }

            var rating = new Rating() { Value = ratingModel.Value, Motorcycle = motorcycle, Author = currentUser };
            motorcycle.Ratings.Add(rating);
            this.Data.SaveChanges();

          var model =this.service.GetRatingViewModel(rating);
            if (model == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }
            
            return this.PartialView("_Rating", model);
        }
    }
}

KTM/KTM.App/Views/Motorcycles/Details.cshtml
@using System.Globalization;
@using KTM.Models.BindingModels
@model KTM.Models.ViewModels.MotorcycleDetailsViewModel
@{
    ViewBag.Title = Model.Title;
}
<h2>@Model.Title <span class="label label-warning">@Model.Rating.ToString("F2", CultureInfo.InvariantCulture)</span></h2>
<hr />
<h4>Category: <a href="~/Categories/Details/@Model.CategoryId" class="btn btn-sm btn-primary">@Model.CategoryName</a></h4>
<div id="rating-container">
    @Html.Action("RatingDetails", "Ratings", new { id = Model.Id })
</div>

<!-- Carousel
================================================== -->
<div class="centre">
    <div id="myCarousel" class="carousel slide">
        <div class="carousel-inner">
            <div class="item active">
                <img src="@Model.ImageUrls.First()">
            </div>

            @foreach (var url in Model.ImageUrls.Skip(1))
            {
                <div class="item">

                    <img src="@url" alt="">

                </div>
            }

        </div>
        <a class="left carousel-control" href="#myCarousel" data-slide="prev"></a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next"></a>

    </div>
</div>
<br />


<h3>@Html.Raw(Model.Description)</h3>


<h3>Engine</h3>

<p>@Html.Raw(Model.Engine)</p>
<h3>Reviews:</h3>
@{
    var reviewModel = new ReviewBindingModel() { EntityId = Model.Id };
}

<div id="new-review">
    @Html.Partial("_AddReview", reviewModel)
</div>

<br />
<div id="reviews-container">
    @if (!Model.Reviews.Any())
    {
        @:
        <p>No reviews yet.</p>
    }
    else
    {
        @Html.DisplayFor(m => m.Reviews)
    }
</div>

KTM/KTM.App/Views/Motorcycles/Index.cshtml
@model IEnumerable<KTM.Models.ViewModels.ConciseMotorcycleViewModel>
@{
    ViewBag.Title = "All Motorcycles";
}

<h2>@ViewBag.Title</h2>
<hr />
@Html.DisplayForModel()
@Html.Partial("_Pagination")

KTM/KTM.App/Views/Motorcycles/_AddRating.cshtml
@model KTM.Models.BindingModels.RatingBindingModel
@if (User.Identity.IsAuthenticated)
{
    <div class="well">
        @Html.ValidationSummary()
        @using (Ajax.BeginForm(
                                    "Add",
                                    "Ratings",
                                    new { id = Model.MotorcycleId },
                                    new AjaxOptions() { UpdateTargetId = "rating-container", InsertionMode = InsertionMode.Replace },
                                    new { id = "add-rating-form", @class = "form-inline" }))
        {
            <label for="rating">Your rating:</label>
            var ratingOptions = Enumerable.Range(1, 5).Select(x => new SelectListItem() { Value = x.ToString(), Text = x.ToString() });
            <div class="form-group">
                @Html.DropDownListFor(m => m.Value, ratingOptions, htmlAttributes: new { @class = "form-control" })
            </div>
                <div class="form-group">
                    <input type="submit" id="add-rating-button" value="Add rating" class="btn btn-primary" />
                </div>
        }
    </div>

}

KTM/KTM.App/Views/Motorcycles/_AddReview.cshtml
@model KTM.Models.BindingModels.ReviewBindingModel
@if (User.Identity.IsAuthenticated)
{
    <div class="row">
        <div class="col-md-12">
            <div class="text-center">
                @Html.ValidationSummary()
                @using (Ajax.BeginForm(
                "Add",
                "Reviews",
                new { id = Model.EntityId },
                new AjaxOptions() { UpdateTargetId = "reviews-container", InsertionMode = InsertionMode.InsertBefore, OnSuccess = "updateReviewForm" },
                new { id = "add-comment-form" }))
                {
                    @Html.TextAreaFor(m => m.Content, new { @class = "form-control", rows = 3, placeholder = "Write a review...", id = "content" })
                    <br/>
                    <input type="submit" id="add-review-button" value="Add review" class="btn btn-primary" />
                }

            </div>
        </div>
    </div>
}
<script>
    function updateReviewForm() {
        $("#no-reviews").hide();
        $("#content").val("");
    }
</script>

KTM/KTM.App/Views/Motorcycles/_Pagination.cshtml
<ul class="pagination">
    @{
        bool isFirstPage = ViewBag.CurrentPage == 1;
        bool isLastPage = ViewBag.CurrentPage == ViewBag.MaxPages;
    }
    <li class="@(isFirstPage ? "disabled" : "")">
        <a href=@(isFirstPage ? "#" : "/Motorcycles?page=1&count=5")>&laquo;</a>
    </li>
    @for (int i = 1; i <= ViewBag.MaxPages; i++)
    {
        <li class="@(ViewBag.CurrentPage == i ? "active": "")">
            @Html.ActionLink(i.ToString(), "Index", new { page = i, count = 5 })
        </li>
    }
    <li class="@(isLastPage ? "disabled" : "")">
        <a href=@(isLastPage ? "#" : "/Motorcycles?page=" + ViewBag.MaxPages + "&count=5")>&raquo;</a>
    </li>
</ul>