KTM/KTM.App/Controllers/CategoriesController.cs
namespace KTM.App.Controllers
{
     using System.Collections.Generic;
    using System.Net;
    using System.Web.Mvc;
    using Data.UnitOfWork;
    using Models.ViewModels;
    using Services;

    public class CategoriesController : Controller
    {
        private CategoriesService service;

        public CategoriesController(IKTMData data)
            : base(data)
        {
            this.service=new CategoriesService();
        }

        public ActionResult All()
        {
      
            var vm = this.service.GetAllCategories();
            if (vm == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }

            Response.StatusCode = 200;
            return this.PartialView(vm);
        }

    
        public ActionResult Details(int id)
        {

       
          var category = this.service.GetCategoryById(id);
           if (category == null)
           {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }


            IEnumerable<ConciseMotorcycleViewModel> vm = this.service.GetDetails(id);
            if (vm == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }
            ViewBag.Category = category.Name;
            Response.StatusCode = 200;
            return View(vm);
        }
    }
}

KTM/KTM.App/Controllers/ChatController.cs
namespace KTM.App.Controllers
{
    using System.Net;
    using System.Web.Mvc;
    using Data.UnitOfWork;
    using Models.ViewModels;
    using Services;

    [Authorize]
    public class ChatController : Controller
    {
       

        private ChatService service;

        public ChatController(IKTMData data)
            :base(data)
        {
            this.service=new ChatService();
        }

        public ActionResult Index()
        {
         //   var currentUser = this.Data.Users.Find(this.User.Identity.GetUserId()).UserName;
            ChatViewModel vm = this.service.GetChatPage();
            if (vm == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }

            Response.StatusCode = 200;
            return View(vm);
        }
    }
}

KTM/KTM.App/Controllers/MotorcyclesController.cs
namespace KTM.App.Controllers
{

    using System.Linq;
    using System.Net;
    using System.Web.Mvc;
    using Data.UnitOfWork;
    using Services;

    public class MotorcyclesController : Controller
    {
        private MotorcycleService service;
       

        public MotorcyclesController(IKTMData data)
             : base(data)
        {
            this.service=new MotorcycleService();
            
        }

      

        public ActionResult Index(int page = 1, int count = 5)
        {

              var motorcycles = this.service.GetAllMotorcycles(page, count);
         
            ViewBag.MaxPages = (this.Data.Motorcycles.All().Count() + count - 1) / count;
            ViewBag.CurrentPage = page;
            var vm = this.service.GetViewModels(motorcycles);
            if (vm == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }
            Response.StatusCode = 200;
            return this.View(vm);
        }

        public ActionResult Details(int id)
        {
           
            var vm = this.service.GetDetails(id);
            if (vm == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }
            Response.StatusCode = 200;
            return this.View(vm);
        }

      
    }
}

KTM/KTM.App/Controllers/NewsController.cs
namespace KTM.App.Controllers
{
    using System.Linq;
    using System.Net;
    using System.Web.Http;
    using System.Web.Mvc;
    using Data.UnitOfWork;
    using Models.ViewModels;
    using Services;

    public class NewsController : Controller
    {
        private NewsService service;
        public NewsController(IKTMData data)
            : base(data)
        {
            this.service=new NewsService();
        }

        public HttpConfiguration Configuration { get; set; }

        public ActionResult Index(int page = 1, int count = 5)
        {
            
            var news = this.service.GetAllNews(page, count);
            ViewBag.MaxPages = (this.Data.News.All().Count() + count - 1) / count;
            ViewBag.CurrentPage = page;
            var vms = this.service.GetConciseNewsViewModels(news);
            if (vms == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }
            Response.StatusCode = 200;
            return this.View(vms);
        }

     public ActionResult Details(int id)
        {
           

            NewsDetailsViewModel vm = this.service.GetDetails(id);
            if (vm == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }
            Response.StatusCode = 200;
            return this.View(vm);
        }

    }
}

KTM/KTM.App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="Content/favicon.ico" type="image/x-icon" />


    <title>@ViewBag.Title - KTM</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")


</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
      
            <a href="@Url.Action("Index", "Home", new {area = ""})" title="KTM" class="links">
                <img alt="KTM" src="https://drive.google.com/uc?id=0ByuTp8DIw-KvRlVSWHNlcUg3Z2s">
            </a>

        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
           
                <li>@Html.ActionLink("All Motorcycles", "Index", "Motorcycles", new {area = ""}, new {@class = "navbar-nav"})</li>
                <li>@Html.ActionLink("All News", "Index", "News", new {area = ""}, new {@class = "navbar-nav"})</li>
                @Html.Action("All", "Categories", routeValues: new {area = ""})
                @if (User.IsInRole("Admin"))
                {
                    <li>@Html.ActionLink("Add Motorcycle", "Add", "Motorcycles", routeValues: new {area = "Admin"}, htmlAttributes: null)</li>
                    <li>@Html.ActionLink("Add News", "Add", "News", routeValues: new {area = "Admin"}, htmlAttributes: null)</li>
                }

                <li>@Html.ActionLink("Contact", "Index", "Contact", new {area = ""}, new {@class = "navbar-nav"})</li>
                <li>@Html.ActionLink("Live Chat", "Index", "Chat", new { area = "" }, new { @class = "navbar-nav" })</li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>
    <br />
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - KTM</p>
        </footer>
    </div>


    <div class="preloader">
        <div id="loop" class="center"></div>
        <div id="bike-wrapper" class="center">
            <div id="bike" class="centerBike"></div>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/js")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/signalr/hubs"></script>


    <script type="text/javascript">
        sessionStorage.setItem('userName', "@HttpContext.Current.User.Identity.Name");
    </script>
@RenderSection("scripts", required: false)


</body>
</html>